spring:
  datasource:
    jdbc-url: jdbc:h2:tcp://localhost/~/sellyourunhappiness
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  profiles:
    active: local

logging:
  level:
    org.hibernate.sql: trace

sellyourunhappiness:
  slack:
    token: T06C30DKWR1/B06EHSJA9GV/EmcTfUsZbizVV5hvtcZ92IzT